create table PANDIT_JI_DTLS(
    PID INTEGER  NOT NULL AUTO_INCREMENT,
    PFIRST_NAME VARCHAR(60) NOT NULL,
    PLAST_NAME VARCHAR(60) NOT NULL,
    PADDRESS VARCHAR(60) NOT NULL,
    PMOBILE VARCHAR(60) NOT NULL UNIQUE,
    PEMAIL VARCHAR(60) NOT NULL UNIQUE,
    DATE DATETIME NOT NULL,
    ISVERIFIED_MOBILE VARCHAR(4) NOT NULL,
    PRIMARY KEY (PID)
)