server:
  port: 9099
eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka

spring:
  application:
    name: OTPVerification
  baselineOnMigrate: true

  jpa:
    hibernate:
      #      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/pandit_ji_booking
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect