CREATE TABLE CUSTOMER_DTLS(
    CUSTOMER_ID LONG,
    CUSTOMER_FNAME VARCHAR(60),
    CUSTOMER_LNAME VARCHAR(60),
    CUSTOMER_ADDRESS VARCHAR(100),
    CUSTOMER_MOBILE VARCHAR(50),
    CUSTOMER_EMAIL VARCHAR(100),
    DATE DATE
);